### PR TITLE
Some improvements. Already used in DP, so merge this allready :D

### PR DESCRIPTION
**Pull request by NPException**

### CODE REVIEW

**Comment by Jezza** [comment]
Could you push them all into one commit?

**Comment by Jezza** [comment]
Just need to squash them.

**Comment by NPException42** [comment]
I don't know how. Can you tell me?

**Comment by NPException42** [comment]
also you could just press the automerge button on the github website ;D

**Comment by Jezza** [comment]
http://stackoverflow.com/questions/7275508/is-there-a-way-to-squash-a-number-of-commits-non-interactively

**Comment by Jezza** [comment]
I'm on mobile, no auto-merge.

**Comment by Jezza** [comment]
Fine. I'll do it...

**Comment by Jezza** [comment]
Ruin my commit history...

**Comment by NPException42** [comment]
Thanks ^^

**Pull request merged**
